'use client';

import { useEffect, useState } from 'react';

export interface EscalationTicket {
  ref_id: string;
  user_id: string;
  student_name: string;
  reason: string;
  issue_summary: string;
  context_checked: string;
  urgency: 'low' | 'medium' | 'high' | 'emergency';
  language: string;
  follow_up_method: string;
  status: 'open' | 'in_progress' | 'resolved';
  created_at: string;
  updated_at: string;
}

interface EscalationsDashboardProps {
  onClose?: () => void;
}

export function EscalationsDashboard({ onClose }: EscalationsDashboardProps) {
  const [tickets, setTickets] = useState<EscalationTicket[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'all' | 'open' | 'in_progress' | 'resolved'>('all');
  const [updatingRef, setUpdatingRef] = useState<string | null>(null);

  const fetchTickets = async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/escalations');
      const data = await res.json();
      setTickets(data.escalations || []);
    } catch (err) {
      console.error('Failed to fetch escalations:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTickets();
  }, []);

  const handleUpdateStatus = async (
    ref_id: string,
    newStatus: 'open' | 'in_progress' | 'resolved'
  ) => {
    try {
      setUpdatingRef(ref_id);
      const res = await fetch('/api/escalations', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref_id, status: newStatus }),
      });
      if (res.ok) {
        setTickets((prev) =>
          prev.map((t) =>
            t.ref_id.toUpperCase() === ref_id.toUpperCase() ? { ...t, status: newStatus } : t
          )
        );
      }
    } catch (err) {
      console.error('Failed to update ticket status:', err);
    } finally {
      setUpdatingRef(null);
    }
  };

  const filteredTickets = tickets.filter((t) => (filter === 'all' ? true : t.status === filter));

  const openCount = tickets.filter((t) => t.status === 'open').length;
  const inProgressCount = tickets.filter((t) => t.status === 'in_progress').length;
  const resolvedCount = tickets.filter((t) => t.status === 'resolved').length;

  const getUrgencyBadge = (urgency: string) => {
    switch (urgency.toLowerCase()) {
      case 'emergency':
        return 'bg-red-500/20 text-red-400 border-red-500/40 animate-pulse';
      case 'high':
        return 'bg-orange-500/20 text-orange-400 border-orange-500/40';
      case 'medium':
        return 'bg-amber-500/20 text-amber-300 border-amber-500/40';
      case 'low':
      default:
        return 'bg-blue-500/20 text-blue-300 border-blue-500/40';
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'resolved':
        return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40';
      case 'in_progress':
        return 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40';
      case 'open':
      default:
        return 'bg-rose-500/20 text-rose-300 border-rose-500/40';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-md">
      <div className="relative flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-3xl border border-white/15 bg-[#0F0F23] shadow-2xl">
        {/* Top Header */}
        <div className="flex items-center justify-between border-b border-white/10 bg-white/5 px-6 py-5">
          <div>
            <div className="flex items-center gap-3">
              <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-[#F97316] to-[#6366F1] text-xl shadow-lg">
                📋
              </span>
              <div>
                <h2 className="text-xl font-extrabold text-white">Teacher Escalation Desk</h2>
                <p className="text-xs font-medium text-white/50">
                  Human support requests generated by EduVoice AI Tutor
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={fetchTickets}
              className="flex items-center gap-1.5 rounded-xl border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-bold text-white/70 transition-all hover:bg-white/10 hover:text-white"
            >
              🔄 Refresh
            </button>
            {onClose && (
              <button
                onClick={onClose}
                className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white/70 transition-all hover:bg-white/10 hover:text-white"
              >
                ✕
              </button>
            )}
          </div>
        </div>

        {/* Status Counter Bar & Filter Switcher */}
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 bg-black/30 px-6 py-3 text-xs">
          <div className="flex items-center gap-2">
            <span className="font-bold text-white/40">Filters:</span>
            <button
              onClick={() => setFilter('all')}
              className={`rounded-lg px-3 py-1 font-bold transition-all ${
                filter === 'all'
                  ? 'bg-orange-500 text-white'
                  : 'bg-white/5 text-white/60 hover:bg-white/10'
              }`}
            >
              All ({tickets.length})
            </button>
            <button
              onClick={() => setFilter('open')}
              className={`rounded-lg px-3 py-1 font-bold transition-all ${
                filter === 'open'
                  ? 'bg-rose-500 text-white'
                  : 'bg-white/5 text-white/60 hover:bg-white/10'
              }`}
            >
              Open ({openCount})
            </button>
            <button
              onClick={() => setFilter('in_progress')}
              className={`rounded-lg px-3 py-1 font-bold transition-all ${
                filter === 'in_progress'
                  ? 'bg-indigo-500 text-white'
                  : 'bg-white/5 text-white/60 hover:bg-white/10'
              }`}
            >
              In Progress ({inProgressCount})
            </button>
            <button
              onClick={() => setFilter('resolved')}
              className={`rounded-lg px-3 py-1 font-bold transition-all ${
                filter === 'resolved'
                  ? 'bg-emerald-500 text-white'
                  : 'bg-white/5 text-white/60 hover:bg-white/10'
              }`}
            >
              Resolved ({resolvedCount})
            </button>
          </div>

          <div className="flex items-center gap-2 font-medium text-white/40">
            <span>Redaction:</span>
            <span className="rounded border border-emerald-500/20 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-bold text-emerald-400">
              🔒 PII Scrubbed
            </span>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 space-y-4 overflow-y-auto p-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className="h-8 w-8 animate-spin rounded-full border-2 border-orange-500 border-t-transparent" />
              <p className="mt-3 text-sm font-semibold text-white/50">
                Loading escalation tickets…
              </p>
            </div>
          ) : filteredTickets.length === 0 ? (
            <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 bg-white/[0.02] py-16 text-center">
              <div className="mb-3 text-4xl">🎓</div>
              <h3 className="text-base font-extrabold text-white">No Escalation Requests Found</h3>
              <p className="mt-1 max-w-sm text-xs text-white/40">
                EduVoice is currently resolving all student questions smoothly without requiring
                human teacher escalation.
              </p>
            </div>
          ) : (
            filteredTickets.map((t) => (
              <div
                key={t.ref_id}
                className="group relative rounded-2xl border border-white/10 bg-white/5 p-5 transition-all hover:border-orange-500/40 hover:bg-white/[0.07]"
              >
                {/* Ticket Top Meta */}
                <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-sm font-extrabold tracking-wider text-orange-400">
                      {t.ref_id}
                    </span>
                    <span
                      className={`rounded-full border px-2.5 py-0.5 text-[11px] font-extrabold uppercase ${getUrgencyBadge(t.urgency)}`}
                    >
                      ⚡ {t.urgency}
                    </span>
                    <span
                      className={`rounded-full border px-2.5 py-0.5 text-[11px] font-bold ${getStatusBadge(t.status)}`}
                    >
                      ● {t.status.replace('_', ' ')}
                    </span>
                  </div>

                  <span className="text-[11px] font-medium text-white/40">
                    {new Date(t.created_at).toLocaleString('en-IN', {
                      dateStyle: 'medium',
                      timeStyle: 'short',
                    })}
                  </span>
                </div>

                {/* Caller & Topic info */}
                <div className="mb-4 grid grid-cols-1 gap-3 rounded-xl border border-white/5 bg-black/30 p-3 text-xs md:grid-cols-2">
                  <div>
                    <span className="mb-0.5 block font-bold text-white/40">
                      👤 Student Information:
                    </span>
                    <p className="font-semibold text-white">
                      {t.student_name}{' '}
                      <span className="font-normal text-white/40">({t.user_id})</span>
                    </p>
                    <p className="text-white/60">
                      Preferred Contact:{' '}
                      <span className="font-medium text-orange-300">{t.follow_up_method}</span> (
                      {t.language})
                    </p>
                  </div>
                  <div>
                    <span className="mb-0.5 block font-bold text-white/40">🚨 Trigger Reason:</span>
                    <p className="font-semibold text-orange-300 capitalize">
                      {t.reason.replace('_', ' ')}
                    </p>
                  </div>
                </div>

                {/* Summary & Context */}
                <div className="mb-4 space-y-2 text-xs">
                  <div>
                    <span className="font-bold text-white/50">📝 Issue Summary:</span>
                    <p className="mt-1 rounded-xl border border-white/5 bg-white/5 p-3 leading-relaxed font-medium text-white/90">
                      "{t.issue_summary}"
                    </p>
                  </div>
                  <div>
                    <span className="font-bold text-white/50">
                      🧠 Agent Context & Topics Checked:
                    </span>
                    <p className="mt-1 rounded-xl border border-white/5 bg-black/20 p-3 font-mono text-[11px] text-white/70">
                      {t.context_checked}
                    </p>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center justify-between border-t border-white/10 pt-3 text-xs">
                  <span className="text-[11px] font-medium text-white/40">
                    Ref ID: <span className="font-mono text-white/70">{t.ref_id}</span>
                  </span>

                  <div className="flex items-center gap-2">
                    {t.status !== 'in_progress' && (
                      <button
                        onClick={() => handleUpdateStatus(t.ref_id, 'in_progress')}
                        disabled={updatingRef === t.ref_id}
                        className="rounded-lg border border-indigo-500/40 bg-indigo-500/20 px-3 py-1.5 font-bold text-indigo-300 transition-all hover:bg-indigo-500/30 disabled:opacity-50"
                      >
                        In Progress
                      </button>
                    )}
                    {t.status !== 'resolved' && (
                      <button
                        onClick={() => handleUpdateStatus(t.ref_id, 'resolved')}
                        disabled={updatingRef === t.ref_id}
                        className="rounded-lg border border-emerald-500/40 bg-emerald-500/20 px-3 py-1.5 font-bold text-emerald-300 transition-all hover:bg-emerald-500/30 disabled:opacity-50"
                      >
                        ✓ Mark Resolved
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
